export const localPhrases = {
  Delhi: {
    howMuchIsThis: "Yeh kitne ka hai?",
    iDontUnderstand: "Mujhe samajh nahi aata",
    canYouHelpMe: "Kya aap meri madad kar sakte hain?",
    excuseMe: "Maaf kijiye",
    whereIsTheBathroom: "Bathroom kahaan hai?",
    whatTimeIsIt: "Kitna baj gaya hai?",
    imHungry: "Mujhe bhookh lagi hai",
    iAmLost: "Main kho gaya hoon",
    iAmFine: "Main theek hoon",
    seeYouSoon: "Jaldi milenge",
    iNeedATaxi: "Mujhe taxi chahiye",
    whatIsYourName: "Aapka naam kya hai?",
    imSorryForTheMistake: "Galti ke liye maaf kijiye",
    whereIsTheStation: "Station kahaan hai?",
    iAmNewHere: "Main yahan naya hoon",
  },
  Bangalore: {
    howMuchIsThis: "Idhu yethra?",
    iDontUnderstand: "Naan artha maadidheera",
    canYouHelpMe: "Neenu nanna sahaya maadabahudaa?",
    excuseMe: "Kshamisi",
    whereIsTheBathroom: "Angala kamra eega?",
    whatTimeIsIt: "Yaava samaya ide?",
    imHungry: "Nanakku oota beku",
    iAmLost: "Naan kadime aayitu",
    iAmFine: "Naan chennagidheeni",
    seeYouSoon: "Kshana kooda nokkuttini",
    iNeedATaxi: "Nanage taxi beku",
    whatIsYourName: "Nimma hesaru enu?",
    imSorryForTheMistake: "Naan thappu maadidini",
    whereIsTheStation: "Station elli ide?",
    iAmNewHere: "Naan illi hosa",
  },
  Mumbai: {
    howMuchIsThis: "Yeh kitne ka hai?",
    iDontUnderstand: "Mujhe samajh nahi aata",
    canYouHelpMe: "Kya aap meri madad kar sakte hain?",
    excuseMe: "Maaf kijiye",
    whereIsTheBathroom: "Bathroom kahaan hai?",
    whatTimeIsIt: "Kitna baj gaya hai?",
    imHungry: "Mujhe bhookh lagi hai",
    iAmLost: "Main kho gaya hoon",
    iAmFine: "Main theek hoon",
    seeYouSoon: "Jaldi milenge",
    iNeedATaxi: "Mujhe taxi chahiye",
    whatIsYourName: "Aapka naam kya hai?",
    imSorryForTheMistake: "Galti ke liye maaf kijiye",
    whereIsTheStation: "Station kahaan hai?",
    iAmNewHere: "Main yahan naya hoon",
  },
  Chennai: {
    howMuchIsThis: "Idhu evvalavu?",
    iDontUnderstand: "Enakku puriyala",
    canYouHelpMe: "Neenga enna udavi seyyala?",
    excuseMe: "Mannikkavum",
    whereIsTheBathroom: "Kaavalaikkada irukku?",
    whatTimeIsIt: "Ezhu mani aachu?",
    imHungry: "Enakku pasikuthu",
    iAmLost: "Naan thirandhaan poga poren",
    iAmFine: "Naan nalamana varugiraen",
    seeYouSoon: "Vazhdhalum sandhippom",
    iNeedATaxi: "Enakku taxi venum",
    whatIsYourName: "Ungal per enna?",
    imSorryForTheMistake: "Enna thappu seidheno mannikkavum",
    whereIsTheStation: "Rathri station ennai veezhndha?",
  },
  Kolkata: {
    howMuchIsThis: "Eta koto?",
    iDontUnderstand: "Ami bujhte parchi na",
    canYouHelpMe: "Apni ki amar shahajjo korte paren?",
    excuseMe: "Maaf korun",
    whereIsTheBathroom: "Bathroom kothay?",
    whatTimeIsIt: "Koto taaj?",
    imHungry: "Ami bhukh peye gechi",
    iAmLost: "Ami bhulie gechi",
    iAmFine: "Ami bhalo achi",
    seeYouSoon: "Abar dekha hobe",
    iNeedATaxi: "Ami ekta taxi chai",
    whatIsYourName: "Apnar naam ki?",
    imSorryForTheMistake: "Ami bhool korechi, maaf korun",
    whereIsTheStation: "Station kothay?",
    iAmNewHere: "Ami ekhane notun",
  },
  Hyderabad: {
    howMuchIsThis: "Idhi entha?",
    iDontUnderstand: "Nenu artham chesukoledu",
    canYouHelpMe: "Meeru naku sahayam cheyyagalara?",
    excuseMe: "Kshaminchandi",
    whereIsTheBathroom: "Bathroom ekkada undi?",
    whatTimeIsIt: "Emi samayam?",
    imHungry: "Naku vanta kavali",
    iAmLost: "Nenu poyinaanu",
    iAmFine: "Nenu bagundaanu",
    seeYouSoon: "Tvaraga malli kaluddam",
    iNeedATaxi: "Naku taxi kavali",
    whatIsYourName: "Mii peru emiti?",
    imSorryForTheMistake: "Thappu chesinaanu, kshaminchandi",
    whereIsTheStation: "Station ekkada undi?",
    iAmNewHere: "Nenu ikkada peddha kaadhu",
  },
  Ahmedabad: {
    howMuchIsThis: "Aavi kitli chhe?",
    iDontUnderstand: "Mane samajhva ma aave chhe",
    canYouHelpMe: "Tame mari madad kari shako cho?",
    excuseMe: "Maaf karo",
    whereIsTheBathroom: "Bathroom kyare chhe?",
    whatTimeIsIt: "Keto samay chhe?",
    imHungry: "Mane bhukh lagi chhe",
    iAmLost: "Mane khoi gayo chhu",
    iAmFine: "Hun saru chhu",
    seeYouSoon: "Jaldi malishu",
    iNeedATaxi: "Mane taxi joiye chhe",
    whatIsYourName: "Tamaru naam su chhe?",
    imSorryForTheMistake: "Galti kari chhe, maaf karo",
    whereIsTheStation: "Station kyare chhe?",
    iAmNewHere: "Hun ahiya navu chhu",
  },
  Jaipur: {
    howMuchIsThis: "Yeh kitne ka hai?",
    iDontUnderstand: "Mujhe samajh nahi aata",
    canYouHelpMe: "Kya aap meri madad kar sakte hain?",
    excuseMe: "Maaf kijiye",
    whereIsTheBathroom: "Bathroom kahaan hai?",
    whatTimeIsIt: "Kitna baj gaya hai?",
    imHungry: "Mujhe bhookh lagi hai",
    iAmLost: "Main kho gaya hoon",
    iAmFine: "Main theek hoon",
    seeYouSoon: "Jaldi milenge",
    iNeedATaxi: "Mujhe taxi chahiye",
    whatIsYourName: "Aapka naam kya hai?",
    imSorryForTheMistake: "Galti ke liye maaf kijiye",
    whereIsTheStation: "Station kahaan hai?",
    iAmNewHere: "Main yahan naya hoon",
  },
  Chandigarh: {
    howMuchIsThis: "Eh kithe da hai?",
    iDontUnderstand: "Main samajh nahi paaya",
    canYouHelpMe: "Ki tusi meri madad kar sakde ho?",
    excuseMe: "Maaf karo",
    whereIsTheBathroom: "Bathroom kithay hai?",
    whatTimeIsIt: "Kithe samay hai?",
    imHungry: "Main bhukhha haan",
    iAmLost: "Main kho gaya haan",
    iAmFine: "Main theek haan",
    seeYouSoon: "Jaldi milange",
    iNeedATaxi: "Mainu taxi chahidi hai",
    whatIsYourName: "Tuhada naa ki hai?",
    imSorryForTheMistake: "Main galti kitti hai, maaf karo",
    whereIsTheStation: "Station kithay hai?",
    iAmNewHere: "Main ithay navaa haan",
  },
  Pune: {
    howMuchIsThis: "Yeh kitne ka hai?",
    iDontUnderstand: "Mujhe samajh nahi aata",
    canYouHelpMe: "Kya aap meri madad kar sakte hain?",
    excuseMe: "Maaf kijiye",
    whereIsTheBathroom: "Bathroom kahaan hai?",
    whatTimeIsIt: "Kitna baj gaya hai?",
    imHungry: "Mujhe bhookh lagi hai",
    iAmLost: "Main kho gaya hoon",
    iAmFine: "Main theek hoon",
    seeYouSoon: "Jaldi milenge",
    iNeedATaxi: "Mujhe taxi chahiye",
    whatIsYourName: "Aapka naam kya hai?",
    imSorryForTheMistake: "Galti ke liye maaf kijiye",
    whereIsTheStation: "Station kahaan hai?",
    iAmNewHere: "Main yahan naya hoon",
  },

  Lucknow: {
    howMuchIsThis: "Yeh kitne ka hai?",
    iDontUnderstand: "Mujhe samajh nahi aata",
    canYouHelpMe: "Kya aap meri madad kar sakte hain?",
    excuseMe: "Maaf kijiye",
    whereIsTheBathroom: "Bathroom kahaan hai?",
    whatTimeIsIt: "Kitna baj gaya hai?",
    imHungry: "Mujhe bhookh lagi hai",
    iAmLost: "Main kho gaya hoon",
    iAmFine: "Main theek hoon",
    seeYouSoon: "Jaldi milenge",
    iNeedATaxi: "Mujhe taxi chahiye",
    whatIsYourName: "Aapka naam kya hai?",
    imSorryForTheMistake: "Galti ke liye maaf kijiye",
    whereIsTheStation: "Station kahaan hai?",
    iAmNewHere: "Main yahan naya hoon",
  },
  Surat: {
    howMuchIsThis: "Aavi kitli chhe?",
    iDontUnderstand: "Mane samajhva ma aave chhe",
    canYouHelpMe: "Tame mari madad kari shako cho?",
    excuseMe: "Maaf karo",
    whereIsTheBathroom: "Bathroom kyare chhe?",
    whatTimeIsIt: "Keto samay chhe?",
    imHungry: "Mane bhukh lagi chhe",
    iAmLost: "Mane khoi gayo chhu",
    iAmFine: "Hun saru chhu",
    seeYouSoon: "Jaldi malishu",
    iNeedATaxi: "Mane taxi joiye chhe",
    whatIsYourName: "Tamaru naam su chhe?",
    imSorryForTheMistake: "Galti kari chhe, maaf karo",
    whereIsTheStation: "Station kyare chhe?",
    iAmNewHere: "Hun ahiya navu chhu",
  },
  Bhopal: {
    howMuchIsThis: "Yeh kitne ka hai?",
    iDontUnderstand: "Mujhe samajh nahi aata",
    canYouHelpMe: "Kya aap meri madad kar sakte hain?",
    excuseMe: "Maaf kijiye",
    whereIsTheBathroom: "Bathroom kahaan hai?",
    whatTimeIsIt: "Kitna baj gaya hai?",
    imHungry: "Mujhe bhookh lagi hai",
    iAmLost: "Main kho gaya hoon",
    iAmFine: "Main theek hoon",
    seeYouSoon: "Jaldi milenge",
    iNeedATaxi: "Mujhe taxi chahiye",
    whatIsYourName: "Aapka naam kya hai?",
    imSorryForTheMistake: "Galti ke liye maaf kijiye",
    whereIsTheStation: "Station kahaan hai?",
    iAmNewHere: "Main yahan naya hoon",
  },
  Indore: {
    howMuchIsThis: "Yeh kitne ka hai?",
    iDontUnderstand: "Mujhe samajh nahi aata",
    canYouHelpMe: "Kya aap meri madad kar sakte hain?",
    excuseMe: "Maaf kijiye",
    whereIsTheBathroom: "Bathroom kahaan hai?",
    whatTimeIsIt: "Kitna baj gaya hai?",
    imHungry: "Mujhe bhookh lagi hai",
    iAmLost: "Main kho gaya hoon",
    iAmFine: "Main theek hoon",
    seeYouSoon: "Jaldi milenge",
    iNeedATaxi: "Mujhe taxi chahiye",
    whatIsYourName: "Aapka naam kya hai?",
    imSorryForTheMistake: "Galti ke liye maaf kijiye",
    whereIsTheStation: "Station kahaan hai?",
    iAmNewHere: "Main yahan naya hoon",
  },
  Varanasi: {
    howMuchIsThis: "Yeh kitne ka hai?",
    iDontUnderstand: "Mujhe samajh nahi aata",
    canYouHelpMe: "Kya aap meri madad kar sakte hain?",
    excuseMe: "Maaf kijiye",
    whereIsTheBathroom: "Bathroom kahaan hai?",
    whatTimeIsIt: "Kitna baj gaya hai?",
    imHungry: "Mujhe bhookh lagi hai",
    iAmLost: "Main kho gaya hoon",
    iAmFine: "Main theek hoon",
    seeYouSoon: "Jaldi milenge",
    iNeedATaxi: "Mujhe taxi chahiye",
    whatIsYourName: "Aapka naam kya hai?",
    imSorryForTheMistake: "Galti ke liye maaf kijiye",
    whereIsTheStation: "Station kahaan hai?",
    iAmNewHere: "Main yahan naya hoon",
  },
  Kanpur: {
    howMuchIsThis: "Yeh kitne ka hai?",
    iDontUnderstand: "Mujhe samajh nahi aata",
    canYouHelpMe: "Kya aap meri madad kar sakte hain?",
    excuseMe: "Maaf kijiye",
    whereIsTheBathroom: "Bathroom kahaan hai?",
    whatTimeIsIt: "Kitna baj gaya hai?",
    imHungry: "Mujhe bhookh lagi hai",
    iAmLost: "Main kho gaya hoon",
    iAmFine: "Main theek hoon",
    seeYouSoon: "Jaldi milenge",
    iNeedATaxi: "Mujhe taxi chahiye",
    whatIsYourName: "Aapka naam kya hai?",
    imSorryForTheMistake: "Galti ke liye maaf kijiye",
    whereIsTheStation: "Station kahaan hai?",
    iAmNewHere: "Main yahan naya hoon",
  },
  Patna: {
    howMuchIsThis: "Yeh kitne ka hai?",
    iDontUnderstand: "Mujhe samajh nahi aata",
    canYouHelpMe: "Kya aap meri madad kar sakte hain?",
    excuseMe: "Maaf kijiye",
    whereIsTheBathroom: "Bathroom kahaan hai?",
    whatTimeIsIt: "Kitna baj gaya hai?",
    imHungry: "Mujhe bhookh lagi hai",
    iAmLost: "Main kho gaya hoon",
    iAmFine: "Main theek hoon",
    seeYouSoon: "Jaldi milenge",
    iNeedATaxi: "Mujhe taxi chahiye",
    whatIsYourName: "Aapka naam kya hai?",
    imSorryForTheMistake: "Galti ke liye maaf kijiye",
    whereIsTheStation: "Station kahaan hai?",
    iAmNewHere: "Main yahan naya hoon",
  },
  Nashik: {
    howMuchIsThis: "Yeh kitne ka hai?",
    iDontUnderstand: "Mujhe samajh nahi aata",
    canYouHelpMe: "Kya aap meri madad kar sakte hain?",
    excuseMe: "Maaf kijiye",
    whereIsTheBathroom: "Bathroom kahaan hai?",
    whatTimeIsIt: "Kitna baj gaya hai?",
    imHungry: "Mujhe bhookh lagi hai",
    iAmLost: "Main kho gaya hoon",
    iAmFine: "Main theek hoon",
    seeYouSoon: "Jaldi milenge",
    iNeedATaxi: "Mujhe taxi chahiye",
    whatIsYourName: "Aapka naam kya hai?",
    imSorryForTheMistake: "Galti ke liye maaf kijiye",
    whereIsTheStation: "Station kahaan hai?",
    iAmNewHere: "Main yahan naya hoon",
  },
  Amritsar: {
    howMuchIsThis: "Eh kithe da hai?",
    iDontUnderstand: "Main samajh nahi paaya",
    canYouHelpMe: "Ki tusi meri madad kar sakde ho?",
    excuseMe: "Maaf karo",
    whereIsTheBathroom: "Bathroom kithay hai?",
    whatTimeIsIt: "Kithe samay hai?",
    imHungry: "Main bhukhha haan",
    iAmLost: "Main kho gaya haan",
    iAmFine: "Main theek haan",
    seeYouSoon: "Jaldi milange",
    iNeedATaxi: "Mainu taxi chahidi hai",
    whatIsYourName: "Tuhada naa ki hai?",
    imSorryForTheMistake: "Main galti kitti hai, maaf karo",
    whereIsTheStation: "Station kithay hai?",
    iAmNewHere: "Main ithay navaa haan",
  },
};
